name: md-davis-dev
channels:
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - python>3
  - biopandas
  - biopython
  - click
  - h5py
  - matplotlib
  - mdtraj
  - numpy
  - pandas
  - plotly
  - pymol=2.2.*
  - scikit-learn
  - scipy
  - toml
  - pip
  - pmw
  - psutil                # required by plotly for png
  - openpyxl              # Required by pandas
  - wxpython

  # packaging requirements
  - pyinstaller
  - setuptools
  - wheel
  - twine

  # linting and checking
  - pylint
  - flake8

  # docs requirements
  - sphinx
  - myst-parser
  - pydata-sphinx-theme
  - sphinx-panels
  - sphinx-click
