name: md_davis_env
channels:
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - python>3.7
  - biopandas
  - biopython
  - click
  - h5py>=3.0
  - matplotlib
  - mdtraj
  - numpy
  - pandas
  - plotly>=4.0
  - pymol-open-source     # replace with pymol-bundle if you have a PyMOL license
  - scikit-learn
  - scipy
  - toml
  - pip
  - psutil                # required by plotly for png
  - openpyxl              # Required by pandas

  # packaging requirements
  - setuptools
  - wheel
  - twine

  # linting and checking
  - pylint
  - flake8

  # docs requirements
  - sphinx>=1.3
  - myst-parser
  - pydata-sphinx-theme
  - sphinx-panels
  - sphinx-click
