name: md_davis_env
channels:
  - conda-forge
  - schrodinger
dependencies:
  - python>3.7
  - biopandas
  - biopython
  - click
  - h5py
  - matplotlib
  - mdtraj
  - numpy
  - pandas
  - plotly
  - pymol-bundle
  - scikit-learn
  - scipy
  - toml

  # Required by pandas
  - openpyxl

  # required by plotly for png
  - psutil
  - python-kaleido

  # packaging requirements
  - setuptools
  - wheel
  - twine

  # linting and checking
  - pylint
  - flake8
