name: md_davis_env
channels:
  - conda-forge
  - schrodinger
dependencies:
  - python>3.7
  - biopandas
  - biopython
  - click
  - h5py
  - matplotlib
  - mdtraj
  - numpy
  - pandas
  - plotly
  - pymol-open-source     # replace with pymol-bundle if you have a PyMOL license
  - scikit-learn
  - scipy
  - toml
  - pip

  # Required by pandas
  - openpyxl

  # required by plotly for png
  - psutil

  # packaging requirements
  - setuptools
  - wheel
  - twine

  # linting and checking
  - pylint
  - flake8
