# This conda environment file is for readthedocs

name: md-davis-doc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - attrdict
  - biopandas
  - biopython
  - click
  - matplotlib
  - mdtraj
  - numpy
  - pandas
  - plotly
  - pymol-open-source
  - scikit-learn
  - scipy
  - pip
  - wxpython
  - h5py
  - toml

  # docs requirements
  - sphinx
  - myst-parser
  - pydata-sphinx-theme
  - sphinx-panels
  - sphinx-click
  - sphinx-tabs
